### Signup - Register a new user
POST http://localhost:8000/api/v1/auth/signup
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "SecurePassword123!"
}

> {%
    client.test("Signup successful", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });

    console.log(response.body.access_token);
    client.global.set("access_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
    console.log("Tokens saved from signup");
%}

###

### Login - Authenticate existing user
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "SecurePassword123!"
}

> {%
    client.test("Login successful", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("access_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
    console.log("Tokens saved from login");
%}

###

### Get Current User - Using stored access token

GET http://localhost:8000/api/v1/auth/me
Authorization: Bearer {{access_token}}

> {%
    client.test("Get user successful", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

